version: '3'

services:
  promtail:
    image: grafana/promtail:2.9.4
    ports:
      - "9080:9080"
    volumes:
      - /var/log:/var/log
      - ./config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9091:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - node_exporter
    restart: always

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - 9101:9100
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3101:3000
    networks:
      - loki
    restart: always

volumes:
  prometheus_data:
    driver: local
  node_exporter_data:
    driver: local