global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9091']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9101']
